### ISSUE TITLE
Print format

### ISSUE THREAD

**Issue by saud-2** [lavaloon-eg/ksa_compliance#102]
I have two units (branches) with different seller name but all invoices of all units get seller name of first unit .

**Comment by mhaggag** [comment]
ZATCA Business Settings are currently at the level of the company. When preparing an invoice for submission to ZATCA, we look up the associated settings by company and use the information defined there. This means to support different units for the same company requires (at the moment) different sites (on separate benches for self-hosting if they have the same VAT, since certs and the like are stored under `sites/` as VAT + extension)

Can you provide more details on the setup in this case to see if we have a workaround? How do invoices specify which unit/branch they're from?

**Comment by saud-2** [comment]
Actually, two units are created as two companies with same VAT and different seller name . in this case do I need a separate benches ?

**Comment by mhaggag** [comment]
OK. This setup is going to run into a problem once you onboard the second company. Currently, the private key and certificate used to sign invoices are stored under `sites/` in the format `{vat_registration_number}.privkey` and `{vat_registration_number}.pem` respectively. The private key is generated during onboarding (the onboard button) and the certificate is written when you retrieve the production CSID. So, the second company to onboard will overwrite the files for the first if they share the same VAT. Invoices generated for both companies will now use the signing information of the second company. ZATCA should reject the invoices for the first company because of an invalid signature.

The reason this might work on frappe cloud (the scenario is not supported so is currently untested), is that it runs docker containers, and my understanding is that each site is going to get its own container. Assuming the containers don't share a volume mounted under `sites/`, each is going to get its own copy of the private key and certificate files. I stress that this is untested and may not work either.

@omarashrafsarhan Please open a work item to track enabling this scenario (different companies with same VAT) or different branches on the same company.

**Comment by saud-2** [comment]
I am now onboarding during simulation and zatca accept invoices from both companies. The issue I faced so far is with print format .

**Comment by mhaggag** [comment]
I'd be wary even if simulation accepts the invoices. Seems more like an oversight or a bug, since we're sending invoices for company A signed with the key of company B.

Regarding the print format, we retrieve the seller name at the very top from the sales invoice company:

```jinja
{% set seller_name, vat_registration_no, street, city, district, postal_code, enable_zatca_integration, type_of_transaction = frappe.db.get_value("ZATCA Business Settings", company, ["seller_name","vat_registration_number", "street", "city", "district", "postal_code", "enable_zatca_integration", "type_of_business_transactions"]) %}
```

Can you double-check the company for the sales invoice in question? Perhaps something is causing all invoices to be recorded on the first company

**Comment by saud-2** [comment]
```javascript
{% set seller_name, vat_registration_no, street, city, district, postal_code, enable_zatca_integration, type_of_transaction = frappe.db.get_value("ZATCA Business Settings", company, ["seller_name","vat_registration_number", "street", "city", "district", "postal_code", "enable_zatca_integration", "type_of_business_transactions"]) %}
``` 
I replaced company with {"company": doc.company} and it's OK now.
What about zatca status mentioned in previous reply ?

**Comment by mhaggag** [comment]
You're right, that's a bug in the print format. I'm confused as to why the invalid line wasn't throwing an exception or returning empty data for all the variables (seller name, etc.). It seems to be returning the value of the last modified ZATCA business settings or something similar, which is why we didn't catch it.

We will make a hot fix for this on the master branch shortly.

**Comment by mhaggag** [comment]
This is fixed in `0.23.3` which was just pushed to master. Please check and let me know if you're still having a problem.

**Comment by saud-2** [comment]
It's OK now.
Thank you.

**Comment by mhaggag** [comment]
Thank *you* for your great reports :smiley: 

FYI, the reason this wasn't blowing up previously is that `company` evaluated to jinja's `Undefined` value of type `DebugUndefined`, which propagated through to frappe's query builder. Since the query builder doesn't understand or handle it (it handles string values and dictionaries), it was dropped from the generated SQL and it just retrieved ZATCA business settings in default order and returned values from the first one returned from the database.

**Comment by mhaggag** [comment]
FYI: We now support multiple branches for the same company `ZATCA Business Settings` but with different CRNs as of [0.41.0](https://github.com/lavaloon-eg/ksa_compliance/blob/master/CHANGELOG.md#0410). It requires setting up branch as an accounting dimension though.

@omarashrafsarhan We should update the wiki if it's not already updated.
