### ISSUE TITLE
Error Creating New Company

### ISSUE THREAD

**Issue by EmkanDevs** [lavaloon-eg/ksa_compliance#153]
Hello,

While trying to create a new company we are getting the following message.

> Message
> Error: Value missing for Mode of Payment: ZATCA Payment Means Code

This was not an issue before the installation of the app.

Help would be appreciated.

**Comment by mhaggag** [comment]
Hello,

The app adds a custom field to mode of payment that defines the equivalent payment means code for ZATCA. When an invoice references a mode of payment, it's translated to the equivalent payment means code when generating XML for ZATCA, so the field is required.

The error is happening because creating a company adds its default account to the list of accounts in the relevant modes of payment; when trying to save the mode of payment after adding the account, it discovers the missing field value.

Please update your modes of payment using [this reference for the payment means codes](https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4461.htm), e.g. cash is 10, bank card is 48.

We'll look into adding this to the [prerequisites](https://lavaloon.com/wiki/system-configuration-nbsp;)

**Comment by EmkanDevs** [comment]
Assigned the values as follows:
Bank Draft = 21
Bank Draft = 54
Cheque = 20
Cash = 10

However, couldn't figure out what the value should be for Wire Transfer...?

Your assistance is greatly appreciated.

**Comment by mhaggag** [comment]
I think the right code for that is 30 for "Credit Transfer", based on Wikipedia's [Wire transfer](https://en.wikipedia.org/wiki/Wire_transfer) page.

**Comment by EmkanDevs** [comment]
Could you please highlight where that was mentioned on the page...? I tried reviewing but couldn't figure out where the code was mentioned...

Thank you.

**Comment by mhaggag** [comment]
Wikipedia mentions three names for wire transfer:
>**Wire transfer**, **bank transfer**, or **credit transfer**, is a method of [electronic funds transfer](https://en.wikipedia.org/wiki/Electronic_funds_transfer) from one [person or entity](https://en.wikipedia.org/wiki/Legal_person) to another.

Searching for credit transfer in the codes, we find 30

**Comment by EmkanDevs** [comment]
Thank you very much!
Much appreciated.
