### ISSUE TITLE
Rejected Invoice

### ISSUE THREAD

**Issue by EmkanDevs** [lavaloon-eg/ksa_compliance#155]
Hello,

Could you please assist in figuring why this invoice was rejected?
Tried reviewing but not sure we understand where the error is as we've managed to create another invoice for the same client using the same configurations and it got accepted with no issues.

Invoice:
[ACC-SINV-2024-00171.pdf](https://github.com/user-attachments/files/17526687/ACC-SINV-2024-00171.pdf)

Error Message:
> ZATCA Message
> {"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[{"type":"WARNING","code":"BR-10","category":"EN_16931","message":"An Invoice shall contain the Buyer postal address (BG-8).Not applicable for simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02).","status":"WARNING"},{"type":"WARNING","code":"BR-KSA-F-06-C23","category":"KSA","message":"[BR-KSA-F-06-C23] - Field character limits for the Buyer Address - Street field (BT-50) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.","status":"WARNING"},{"type":"WARNING","code":"BR-KSA-F-06-C25","category":"KSA","message":"[BR-KSA-F-06-C25] - Field character limits for the Buyer Address - City field (BT-52) have not been met. The minimum limit is 1 character and the maximum limit is 127 characters.","status":"WARNING"},{"type":"WARNING","code":"BR-KSA-10","category":"KSA","message":"Buyer address must contain a street (BT-50), city (BT-52), country code (BT-55). This rule does not apply on the simplified tax invoices and associated credit notes and debit notes (KSA-2, position 1 and 2 = 02). ","status":"WARNING"}],"errorMessages":[{"type":"ERROR","code":"BR-CO-15","category":"EN_16931","message":"Invoice total amount with VAT (BT-112) ","status":"ERROR"},{"type":"ERROR","code":"BR-CO-14","category":"EN_16931","message":"Invoice total VAT amount (BT-110) ","status":"ERROR"}],"status":"ERROR"},"clearanceStatus":"NOT_CLEARED","clearedInvoice":null}

Thank you!

**Comment by mhaggag** [comment]
Hello,

The warnings are the result of a missing or incorrectly defined buyer address (customer address). This is retrieved from the customer address set on the invoice (field `customer_address`).

The error indicates tax calculation is wrong, but it appears clipped. Can you check the `Sales Invoice Additional Fields` for this invoice and attach or paste its XML content and validation warnings/errors (if any), minus any sensitive details? (Also, please review the PDF invoice attached for sensitive details--it appears to contain bank accounts and similar info that you may not want to be public)

**Comment by EmkanDevs** [comment]
PDF edited (Thanks for the heads up!).

Requested XML:
[ACC-SINV-2024-00174-AdditionalFields-175.txt](https://github.com/user-attachments/files/17526713/ACC-SINV-2024-00174-AdditionalFields-175.txt)

**Comment by mhaggag** [comment]
The XML is for invoice 00174 while the PDF is for 00171. We currently don't offer a direct link from the sales invoice to the associated additional fields, but you can filter with the "Invoice" in the `Sales Invoice Additional Fields` list to get the proper document(s).

Also, can you check whether there's a difference between the total in `Sales Taxes and Charges` and the `Grand Total` as reported/shown in [this erpnext bug](https://github.com/frappe/erpnext/issues/43143)?

**Comment by EmkanDevs** [comment]
Apologies about that.
[ACC-SINV-2024-00171-AdditionalFields-170.txt](https://github.com/user-attachments/files/17534083/ACC-SINV-2024-00171-AdditionalFields-170.txt)

**Comment by BOTSolutions8686** [comment]
The error is because of the tax calculation. 
Tax amount in one place is showing as 
.93 
And in another 
.94 

Is the rounding turned on ?

**Comment by mhaggag** [comment]
Can you see that difference in the sales invoice itself, or only in the additional fields?

**Comment by EmkanDevs** [comment]
Rounding is disabled.
![image_2024-10-28_105728013](https://github.com/user-attachments/assets/489d7254-3572-4cc1-9b1a-fa1d337f8d18)

**Comment by mhaggag** [comment]
This is an issue with general floating-point calculation precision and rounding, not related to the rounded total checkbox. Can you share which version of ksa_compliance do you currently have?

Also, can you open the invoice line details and check whether you have the fields "Tax Rate", "Tax Amount", and "Total Amount" and share their values (screenshot if available)? Also, please share a screenshot of the `Tax Breakup` section

This could be either the ERPNext bug linked above, or a bug arising from the way we're calculating line-level information in ksa_compliance. Prior to version 0.38.0 of ksa_compliance, we used to computed the line-level tax amount ourselves. This sometimes leads to different results from ERPNext because we weren't doing it with the same precision. Version 0.38.0 adds the three fields mentioned above (tax rate, amount, and total amount) to `Sales Invoice Item` which causes ERPNext to automatically calculate and fill the fields. ksa_compliance then uses them, which should ensure they're the same as ERPNext.

**Comment by EmkanDevs** [comment]
At the time of the issue we were on 0.37.2 but just upgraded to the latest 0.39.1 before seeing your last reply. Not sure if that would make a difference now...?
Should we check for the same things mentioned in your reply? or are there different steps to follow in this case?

**Comment by mhaggag** [comment]
Let's follow the same steps. You should be on the latest, but if you didn't have the line-level fields when you generated the invoice, they're going to be filled with zeroes.

**Comment by EmkanDevs** [comment]
Please see below:
![image_2024-10-28_152409534](https://github.com/user-attachments/assets/0a445c20-60dc-4b2c-9a68-2483b692f353)

Also, CSV of the line item in question. Only 1 item in the invoice.
[Items.csv](https://github.com/user-attachments/files/17542298/Items.csv)

Tax Breakup:
![opera_g3d429kIpE](https://github.com/user-attachments/assets/ca0d6a93-35e5-4d6b-9c3b-52daf1652dc1)

**Comment by mhaggag** [comment]
Is the tax included in the base rate in this case?

**Comment by EmkanDevs** [comment]
Can't find any indication of that being the case.

**Comment by mhaggag** [comment]
OK. So the next step is to see if regenerating XML for ZATCA on 0.39.1 fixes the issue, but the problem is that it'll try to do it from the zeroed fields on the sales invoice item (tax_rate and tax_amount specifically). Do you have access to the database console to set the proper values on those fields?

**Comment by EmkanDevs** [comment]
Yes. Would be possible to access the database. What changes would need to be made?

**Comment by mhaggag** [comment]
We need to update the `Sales Invoice Item`'s three fields: `tax_rate`, `tax_amount`, and `total_amount` to the right values. That'd be `15.0`, `946.94` and `7259.84` in this case.

First, you'd figure out the ID of the Sales Invoice Item. Since it's only one line in the invoice, you can just do:
```sql
SELECT name FROM `tabSales Invoice Item` where parent = 'ACC-SINV-2024-00171'
```

Then update it to the proper values:
```sql
UPDATE `tabSales Invoice Item` SET tax_rate = 15.0, tax_total = 946.94, total_amount = 7259.84 WHERE name = '<name returned from previous select>'
```

**Comment by mhaggag** [comment]
Hello,

Is this resolved?
