### ISSUE TITLE
How can i manage branches and every branch has same TAX ID but different CR

### ISSUE THREAD

**Issue by hamzahabdo** [lavaloon-eg/ksa_compliance#168]

**Comment by mhaggag** [comment]
Hello,

We don't support different settings per branch because `Sales Invoice` doesn't contain a branch specifier, so we can't lookup the corresponding settings if different branches were used.

One way to implement this is to use a company per branch so it can have its own `ZATCA Business Settings`, where you can add the CRN in the seller info.

**Comment by omarashrafsarhan** [comment]
This feature is now available in app version 0.41.1 and later. I will proceed with closing this issue.
